name: minimal
description: A minimalistic Flutter website template for blogs and portfolios.
version: 1.5.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^10.0.0
  google_fonts: ^5.0.0
  loading_gifs: ^0.3.0
  responsive_framework: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  riverpod_lint: null
  custom_lint: null
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/Minimal-Logo.png"
  image_path_ios: "assets/Minimal-Logo-iOS.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/Minimal-Logo-Adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
